theodo_imagine_formation:
    resource: "@TheodoImagineFormationBundle/Controller/"
    type:     annotation
    prefix:   /

theodo_imagine_formation_demo:
    resource: "@TheodoImagineFormationBundle/Resources/config/routing.xml"
    prefix:   /
